### ISSUE TITLE
Search Results Randomly Break Styles

### ISSUE THREAD

**Issue by krjordan** [CodeSequence/sanmyaku#36]
Search result styling is randomly breaking due to the `<li>` sometimes being placed outside the `<ol id="search-results">` along with `.page-sidebar` being randomly placed inside an `<li>`. 

Unable to reproduce locally.

**Comment by valeryan** [comment]
This is a vanilla bug. My fix for it was merged into vanilla core but it want be included until the next release of vanilla.  See https://github.com/vanilla/vanilla/pull/3591
