### ISSUE TITLE
wrong images path

### ISSUE THREAD

**Issue by kintaro1981** [CodeSequence/sanmyaku#38]
hello,

I installed vanilla in the subdirectory vanilla and then installed sanmyaku theme but all the image link are broken.

in the theme images are linked like:
https://domain.com/themes/sanmyaku/design/images/open-menu.svg
instead of:
https://domain.com/vanilla/themes/sanmyaku/design/images/open-menu.svg

**Comment by krjordan** [comment]
What does your file structure look like? The image paths are correct and should work fine.

**Comment by kintaro1981** [comment]
my vanilla installation path is:
domain.com/vanilla/

**Comment by krjordan** [comment]
I'll look into a better solution for this. If you have any ideas, feel free to open a PR.

**Comment by valeryan** [comment]
@krjordan I think maybe we should look at adding all the images encoded to a css file and load those instead of images from the design dir. Some of these strings might be huge but it would make the images dir agnostic.

**Comment by krjordan** [comment]
@valeryan The browser support looks good for base64 encoding. Should work well for the icons and what not. Although I have concerns with the sub-header and footer image's file size. I'll check into it.

**Comment by lukehowell** [comment]
If you know where the final css files are going to be would it not be better just to do this relatively.  CSS urls can handle relative urls.  Here are a couple examples of the leading slash breaking functionality with vanilla installed in a subdirectory.

```
./app/scss/partials/custom_components/_optionsMenu.scss:108:        background-image: url(/themes/sanmyaku/design/images/icons/forum.bookmark.active.svg);
./app/scss/partials/custom_components/_optionsMenu.scss:111:        background-image: url(/themes/sanmyaku/design/images/icons/forum.bookmark-main.svg);
./app/scss/partials/custom_components/_post-bg.scss:8:      background: url(/themes/sanmyaku/design/images/dark/post-bg.png) center;
./app/scss/partials/custom_components/_search-results.scss:20:      background: url(/themes/sanmyaku/design/images/icons/forum.search-icon.svg) no-repeat center;
./app/scss/partials/custom_components/_search-results.scss:27:        background-image: url(/themes/sanmyaku/design/images/icons/forum.search-icon.active.svg);
```

**Comment by R-J** [comment]
If you were using php, you could use Vanillas helper functions:
url()
img()
smartAsset()

All of them would take care for building urls that are valid for forums in root folder and forums in sub folders. There is no custom Smarty function enclosed which offers this functionality. Writing one is quite easy, though. I've created a custom Smarty function for smartAsset and changed the default.master.tpl to already use it. See this PR: https://github.com/CodeSequence/sanmyaku/pull/51
