### ISSUE TITLE
Unable to build with Gulp

### ISSUE THREAD

**Issue by krjordan** [CodeSequence/sanmyaku#40]
When running `gulp build` or `gulp` I get a `Bus error: 10` and I'm unable to build the theme. I've tried multiple version of node (4, 5 and 6).

**Comment by lukehowell** [comment]
The error seems to be cause in [line 103 of _tab-bar.scss](https://github.com/CodeSequence/sanmyaku/blob/master/app/scss/partials/custom_components/_tab-bar.scss#L103).  If I remove either `#{$tabbar-height}` or `#{$profile-size}` the error goes away.  (note: there are other errors that appear but are regular scss errors).  

A mixin nested inside itself is supposed to be one cause for `bus error 10` but I have yet to figure out what part of this line is causing the problem.

**Comment by lukehowell** [comment]
It appears to be the number of arguments in the sass calculation.  If I change it to the following it doesn't fail.

```
right: calc(#{$tabbar-height} + #{$profile-size} + (#{rem-calc(22)} * 2));
```

or the following also works

```
right: $tabbar-height + $profile-size + rem-calc(22) + rem-calc(22);
```
