### ISSUE TITLE
White Page after enabling the theme

### ISSUE THREAD

**Issue by ntimo** [CodeSequence/sanmyaku#44]
Hi there,
I am using the latest version of Vanilla Forums. And everytime I try to enable your theme and then open the / page of my forum I just get a white page with no content :/

**Comment by valeryan** [comment]
@ntimo several things can cause this. First we need to know the specific version of vanilla you are running. is it 2.2.1 downloaded from vanilla addons or is it from the vanilla git repo? Are you running php 7? Are you using the download of the theme from vanilla addons or are you using the git repo? Have you followed our build steps if your are? 

For instance, I am running a fresh build of vanilla 2.2.1 downloaded and built from vanilla's repo with a fresh copy of our theme dowloaded and built using php 5.6. The theme loads without issues. I will need specifics from you to try and reproduce your error. 

Thanks

**Comment by ntimo** [comment]
okay, I fixed it. The name of the folder contanting the theme had the wrong name. But now I found out that the latest version you provide on vanilla forums misses the design folder so I took one from an older version to make the theme work :)

**Comment by valeryan** [comment]
vanilla 2.2.1 does not officially support php 7 so you may have issues with vanilla. Also running with and old design folder is not a great idea. The build process is not very difficult to build a new design folder. Just follow the readme on this repo. We will look at replacing or rereleasing the update with the design folder included.
