### ISSUE TITLE
Copyright (follow-up, please answer ASAP)

### ISSUE THREAD

**Issue by aarong2003** [CodeSequence/sanmyaku#47]
Hi,
Thanks for your responses. I really appreciate it. I wanted to use the theme for my website debateisland.com. It's through vanilla. Your theme looks really nice so I wanted to consider using it. Good job on the theme. Please let me know if I can use it form my website without the copyright.
Thanks, Aarong

**Comment by krjordan** [comment]
> Sure, go for it.

https://github.com/CodeSequence/sanmyaku/issues/45#issuecomment-266310853

We will edit the license soon, but in the mean time, yes. You may change and/or remove the copyright as long as you are using it on your own site. In this case, your forum.
