### ISSUE TITLE
open-menu.svg

### ISSUE THREAD

**Issue by omololuwa** [CodeSequence/sanmyaku#48]
I installed your Vanilla "**Sanmyaku version 1.0.3**" theme on Vanilla 2.3, but the "**open-menu.svg**" does not display on all browsers on MacOS and Windows 10 (see attached screenshot). Could you please guide me to how to resolve this issue.

Best Regards.

Lolu

![screen shot 2017-02-28 at 8 22 23 am](https://cloud.githubusercontent.com/assets/13490907/23395701/4fc7bb98-fd90-11e6-8de6-58d37380747c.png)

**Comment by krjordan** [comment]
This is most likely related to #38, but I'm not sure why the background image is displaying. Are any other icons not displaying or is it just the `open-menu.svg`?

**Comment by omololuwa** [comment]
Thanks, krjordan, for your response.

Please, could you post a screenshot that shows other icons ... I can't seem to see any other icon. It is just the **open-menu.svg** I note that is not displaying. Could you also please direct me to the script(s) folders and the scripts responsible for the various displays of the theme. Meanwhile, I'll have a look at previous post https://github.com/CodeSequence/sanmyaku/issues/38 as indicated in your post.

Best Regards.

Lolu

**Comment by omololuwa** [comment]
Hi Ryan,

Thanks for your response. I posted a response on GitHub yesterday March 1.

I'm posting the black background version of your theme and I can confirm
that the icons images are correctly displayed (see the attached
screenshot). Meanwhile, I have had a look at previous post #38
<https://github.com/CodeSequence/sanmyaku/issues/38> as indicated in your
post, but I'm still not able to resolve this issue. Is it feasible for you
to send a copy of the theme by Email. Do you have other themes you may
please wish to share with me ?

Best Regards.

Lolu

**Comment by krjordan** [comment]
It's working for me on both the light and dark versions theme. You might need to edit the path to the image depending on how you have you Vanilla instance set up. To do so, you can edit lines 16 and 34 in the `views/default.master.tpl`. The version you have (`1.0.3`) is up to date.

**Comment by omololuwa** [comment]
Hi Ryan,

This was the path to the image in both lines 16 and 34;

<img class="hamburger" src="/themes/sanmyaku/design/images/open-menu.svg"
alt="">, but when I included my Vanilla folder in the path, it WORKED !!!
Thank you very very much.

I have another little issue. When I *Signout* on the white background
version, the *avatar-placeholder.svg* shows (see attached screenshot),
however it does not show in the case of the black background version (see
attached screenshot). The reason is that this image is in black color. If
the color is in grey or even dimgrey color, it would definitely show. What
do you suggest that I do ?

I do have a few suggestions I want to make for the theme to suit my forum
implementation features plan. Do you advise that I post these suggestions
on GitHub or directly to you through this Email channel ?

Once again, thank you.

Regards.

Lolu

**Comment by krjordan** [comment]
I get the impression that you are responding to the email notifications sent from GitHub and attaching the screenshots to the email. These aren't showing up in the GitHub comment that you are commenting on. If you want to attach screenshots, you should do so on the GitHub website.

Also, if you have other issues that aren't related to this issue, please open another issue on GitHub and I will be happy to take a look. This helps other people who might have the same issue when they search for that particular issue.

Any suggestions or feature requests should be added as a new issue and you are welcome to submit a Pull Request for review.

**Comment by omololuwa** [comment]
Yes, you are right, I was responding to your mail from my private Email account ... sorry about that. I note that this issue #48 has now been resolved and closed. The new issue I mentioned in my earlier response seems irrelevant now because it was a situation of my eyesight not being able to see the grey **avatar-placeholder.svg** ... it is OK now. 

I'll do a new issue or submit a Pull request on any suggestions or feature requests that I have.

Thanks.

Lolu
