### ISSUE TITLE
theme issue 2.3

### ISSUE THREAD

**Issue by codiii** [CodeSequence/sanmyaku#50]
I love this theme its the best thats out there..  but running into issues

1# issue when you click post new discussion the right side disappears
2# the latest post that is show in the preview I cannot find it the one i did dont work.
3# the users online text not the user online image version dont work.

I use foundation 6 I love this theme because it uses foundation.

**Comment by codiii** [comment]
where can i find the forums stats plugin?

**Comment by codiii** [comment]
sad guess this theme is done

**Comment by krjordan** [comment]
This is being investigated, but in the meantime, I'd be happy to review a PR for a fix! 😉 

As far as the forums stats plugin, I'm not sure what you are referring to. Can you be a bit more specific?

**Comment by codiii** [comment]
yes if you look at the plugins  list for this theme https://github.com/CodeSequence/sanmyaku/blob/master/plugins.md    it shows a forumstats 2.3 plugin but have not been able to locate it.

the 2 biggest issues is that in the preview on here there is a latest discussions in the sidebar but on mine it don't show. and when you click on new discussion the sidebar does not display

**Comment by krjordan** [comment]
The Forum Stats and Discussion Sidebar plugins have yet to be released. We hope to have the plugins, along with a few other, released in a few weeks. Feel free to watch this project on GitHub. We'll update the `plugins.md` as each is released.

cc @valeryan

**Comment by codiii** [comment]
they have yet to be released ? i have seen a site using them... what about the sider bar disappearing when you click new topic. it dont do it in an older version of vanilla

**Comment by codiii** [comment]
@krjordan 

you say its not released yet but you have the latest discussions in the preview here http://sanmyaku.krjordan.co/index.php?p=/

**Comment by krjordan** [comment]
@codiii you are correct. The preview site for this theme is using these plugins, however these plugins have not yet been released. These custom plugins were created by @valeryan who also helped create this theme. When time permits, hopefully in a few weeks, this issue will be resolved and the plugins should be released to the public.

**Comment by valeryan** [comment]
@codiii The plugins in question are custom plugins that I built for us internally that I plan to release to the public. I have not had the time to go through them and get the ready for public release. I work full time and go to collage full time so I have not had the time to get them in a ship-able state but I graduate in a few weeks so I should get some time to work on them. However, I plan to rewrite the plugins to be a single package that is a sanmyaku theme addon that provides the extra functionality. The demo site has the plugins because we have them and we can use them but they are not ready for public release. 

Both @krjordan  and I are getting 2.3 systems up and running and will be taking a better look at how it affects the theme in a few weeks. However, the theme problems are most likely css or js related so if you have the issues and you can analyze possible breaks and help to identify any behavior that needs to be looked at, we would love to field your pull request.

**Comment by codiii** [comment]
@valeryan I understand I just know of a site that has had them for about a year and was interested.. the only issue I am faced with in version 2.3 I have looked everywhere but cannot find anything..  the sidebar has issues in post discussion, search, New Message everything is pushed to the left like the sidebar is there but nothing shows in it. and the back ground color for the inbox  new message in side bar is fine but if  click new message the box color around the but in new message is not showing just button.. looks great in 2.2 just trying to fix it in 2.3

**Comment by valeryan** [comment]
@codiii we will look in to those issues. Thanks for you pointing them out. I am curious to know what site you have seen with my plugins beyond the demo site. I only know of one other possible site.

**Comment by codiii** [comment]
https://forum.americasarmy.com/

**Comment by codiii** [comment]
@valeryan https://forum.americasarmy.com/

**Comment by valeryan** [comment]
@codiii Do you play America's Army? 

The forum at america's army has a custom version of this theme that @krjordan built and all of my custom plugins for a very specific reason. Until I have to time to rewrite them all as completely open source they will not be released. My intentions where to release them a long time ago but life has not played out that way.

**Comment by R-J** [comment]
@valeryan: I just had a look at a similar plugin and found that it wasn't caching any of its results. I don't know how you have gathered statistic information in your plugin, but I think a plugin like that [could really benefit from caching](https://github.com/R-J/ReusableStats/blob/master/class.reusablestats.plugin.php#L165-L186).
Even if you haven't cleaned up the code: if you put the source code here I would happily assist if I can and you want me to.

**Comment by codiii** [comment]
@valeryan yes I do and Battlefield 1 lol

**Comment by codiii** [comment]
I love the theme because I love foundation not a fan of bootstrap

**Comment by codiii** [comment]
@valeryan how much would you charge for a simple theme using foundation 6? its pretty simple i have no idea about smarty not since php nuke days lol

**Comment by valeryan** [comment]
@codiii, @R-J I don't have any of the source code for the extensions that I wrote while I was working on Americas Army at the Army Game Studio. I also am not using Vanilla these days and I have not stayed up to date on its current capabilities. I was able to get this theme to build with the new changes from #58 though so maybe these issues are gone maybe not ...
