### ISSUE TITLE
Search and post sidebar version 2.3.1

### ISSUE THREAD

**Issue by 2Epic** [CodeSequence/sanmyaku#53]
I came across your them and i like the fact that its foundation.. my issue is where can i find the part for the new discussion and the search the side bar does not show on either one but it takes up the space like it is there.. I looked at it using inspector and it says in the side bar  
in the sidebar div.. but I have been unable to locate those 2 parts search and where you post discussion. I am confused as to why only those to sidebar pages are not working.

**Comment by valeryan** [comment]
@2Epic We are looking for a maintainer for this theme. We have not used Vanilla in a long time and I don't have any methods of testing what you are seeing. A new release was just posted that should make the theme run in Vanilla 2.6 but it is untested. It may or may not fix your issues but we are closing this for now.
