### ISSUE TITLE
Sidebar Icons

### ISSUE THREAD

**Issue by ghost** [CodeSequence/sanmyaku#54]
![image](https://user-images.githubusercontent.com/34454156/34121532-5a4369a2-e3f7-11e7-9bb8-d2c300590f2e.png)
If you look at this image, when i uploaded your theme, the sidebar icon did not work? Is there any reason as to why?

**Comment by valeryan** [comment]
We just drafted a new release that should get the theme to load in Vanilla 2.6 but we are not able to test it. We are looking for a new maintainer. Feel free to reach out with a PR for any problems you have that you can find a fix for.
